baseURL = "https://bianchitom.github.io"
languageCode = "en-us"
title = "terminal-bianchitom"
theme = "hugo-theme-terminal-cookbook"

# optional, if you want to use plain html
# in your markdown recipe files
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
